name: Run Pester Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  pester-tests:
    name: Run Pester tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Run all Pester tests
        shell: pwsh
        run: |
          Install-Module -Name Pester -MinimumVersion 5.3.0
          Install-Module -Name PoshPacli -Force
          Invoke-Pester .\Tests\*.Tests.ps1 -Passthru